### ISSUE TITLE
Using wildcards in folder name

### ISSUE THREAD

**Issue by marabum** [Sebane1/PenumbraModForwarder#3]
Hi,

is it possible, or would it be possible to implement, a way to use wildcards in the download directory? A lot of mods come as .zip files and so we're stuck adding them manually anyway. 

Think something like, setting `C:\Downloads\**` as the download folder within the Forwarder to recursively find mods inside folders.

**Comment by Sebane1** [comment]
I have come up with a different solution for this as of v1.0.0.8. 

Penumbra Mod Forwarder will now read through newly downloaded .zip, .rar, or .7z files as if they are actual folders and extract out the relevant mods archives before then sending them to penumbra.
