### ISSUE TITLE
[Releases] Download link 404s

### ISSUE THREAD

**Issue by zbee** [Sebane1/PenumbraModForwarder#61]
The "Download the zip" link in releases 404s: https://github.com/Sebane1/PenumbraModForwarder/releases/tag/v1.0.1.3

It links to:
```
https://github.com/Sebane1/PenumbraModForwarder/blob/v1.0.1.3/PenumbraModForwarder.zip
```

Whereas the actual zip is:
```
https://github.com/Sebane1/PenumbraModForwarder/releases/download/v1.0.1.3/PenumbraModForwarder.zip
```

**Comment by ErrorDodo** [comment]
There is a PR about this.

Will be merged in today 
#60
